import:
  - ~/.config/alacritty/dracula/dracula.yml
  # uncomment the flavour you want below:
  # - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-latte.yml

window:
  decorations:
    none
  padding:
    x: 10
    y: 10
  # opacity: 0.9
  # startup_mode: Fullscreen 
  #font:
  # normal:
  # bold:
  # italic:

env:
  TERM: xterm-256color

font:
  normal:
    family: NotoSansMono Nerd Font 
  bold:
    family: NotoSansMono Nerd Font 
  italic:
    family: NotoSansMono Nerd Font 

cursor:
  style:
    shape: Beam
  blinking: Off

working_directory: None

#shell:
#  program: /bin/zsh
#args:

# alacritty VI mode
