# Colors (Gruvbox Material Dark Medium)
colors:
  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'


#import:
#  - ~/.config/alacritty/dracula/dracula.yml
  # uncomment the flavour you want below:
  # - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-latte.yml

window:
  # decorations:
  #   none
  padding:
    x: 10
    y: 10
  # opacity: 0.8
  # startup_mode: Fullscreen 
  #font:
  # normal:
  # bold:
  # italic:

env:
  TERM: xterm-256color

font:
  normal:
    family: NotoSansMono Nerd Font 
  bold:
    family: NotoSansMono Nerd Font 
  italic:
    family: NotoSansMono Nerd Font 
  size:
    14

cursor:
  style:
    shape: Beam
  blinking: Off

working_directory: None

#shell:
#  program: /bin/zsh
#args:

# alacritty VI mode
